### PR TITLE
[WIP] Return local insertions and deletions

### PR DESCRIPTION
**Pull request by FrancisBehnen**
This adds support to return local insertions and deletions, for users that have two way communication with their remote storage. I'm not sure if you want to go this way with the library @3lvis, so I've pushed it to my fork first. I can finish it in my fork, or, if you'd like to help, you may want to merge it to a new branch in this repo.

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
I have thought about giving the locally created and deleted objects back via closures just like the remote inserted and deleted objects, but it made more sense to me to return them. It's pretty likely that the user has to do some preparation before it can send the locally created and deleted objects to his remote API. I'm afraid that if this would also have to be done in a closure it would end up messy. Besides that it also felt more natural than 'closuring' :p

**Comment by 3lvis** [comment]
Hi @FrancisBehnen, would you mind sharing a use case for this? In which cases this would be useful?

**Comment by FrancisBehnen** [comment]
This will be my own (first) use case: "I have an app that keeps a copy of a remote database because I want the app to work offline. The remote database can change (insertions/deletions), but the user should also be able to do insertions and deletions from within the app, so the local database can also change. I want the app to work offline so I have to keep track of the local insertions and deletions (in this implementation this is done by changing the `syncStatus`) until the phone gets online again and I can sync with the remote database."
As far as I know this is not possible with the `Sync` library right now. If we add this to `DATAFilter` with an accompanying implementation in `Sync` a user that wants the described behaviour only needs one call to `Sync.changes()` for all his database needs.

**Comment by FrancisBehnen** [comment]
Let me know what you think and/or if you need additional explanation.

**Comment by 3lvis** [comment]
Hi @FrancisBehnen,

I understand your use case, would be awesome to help to fix this issue in Sync. I will have to give it some thought on what would be the best approach. So far I have been quite shy on adding another required Core Data attribute to make things work. The only required attribute at the moment is `remoteID` and it's only on `Sync`. I think all the other dependencies are agnostic of this and I would love to keep it this way.

**Comment by FrancisBehnen** [comment]
I totally get your concern.  I simply couldn't think of another way to do it ([I didn't even come up with this one myself :p](https://www.raywenderlich.com/15916/how-to-synchronize-core-data-with-a-web-service-part-1)). 

Do consider though that the added functionality is no breaking change in any way. If you remove the attribute from the `xcdatamodel` the tests that test the functionality currently in master all pass. We could decide to just add the functionality added in this PR as some extra functionality that we offer for users that need it, but doesn't bother current users and future users that don't need it.

Since we do need persistent storage of some sort I can only think of two ways to remove the dependency.
The simplest solution would be to add an attribute programmatically, but this is probably not possible. 
Another way to get rid of the dependency would be to [add an entire entity programmatically](http://stackoverflow.com/questions/35227132/create-entity-programmatically-core-data), which would mean we will have to link the users entries to the entries in our entity. On top of that we might even have to [copy the whole `moc`](http://stackoverflow.com/questions/29908435/create-core-data-entities-dynamically-during-runtime) if the user didn't let us add the entity before initializing his `moc`.

**Comment by Fr4nc3sc0NL** [comment]
I guess this has to be updated for Swift 3 too.. :/ I'll do that somewhere in the upcoming weeks. In the meantime: have you had any thoughts on this?

**Comment by FrancisBehnen** [comment]
I guess this has to be updated for Swift 3 too.. :/ I'll do that somewhere in the upcoming weeks. In the meantime: have you had any thoughts on this?

**Comment by 3lvis** [comment]
Hey! I'm sorry if I haven't had the time to look at this. I've been pretty busy at work.

I understand the idea but I'm having a hard time thinking how this would be used in an app. Do you have time for a Skype talk this week? Let's figure out the best way to add this. I'm sure this is a good idea, just wondering on the best way to do it.

**Comment by FrancisBehnen** [comment]
I don't have time for a Skype call this week, but somewhere next week should be ok. I got the idea of the `syncStatus` attribute from https://www.raywenderlich.com/15916/how-to-synchronize-core-data-with-a-web-service-part-1. So you might have a look at their demo project to get an idea of how you use it in an app.

**Comment by 3lvis** [comment]
Fantastic!

**Comment by 3lvis** [comment]
I had a look at what the article does and I think it can be achieved using the current DATAFilter setup, basically we need to add to the predicate the fact that we have to skip attributes with `syncStatus != synced`.

**Pull request closed without merging**
